import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./vendor.css";
import Script from "next/script";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Script src="/js/jquery-3.5.1.min.js" strategy="lazyOnload" />
        <Script src="/js/bootstrap.bundle.min.js" strategy="lazyOnload" />
        <Script src="/js/owl.carousel.min.js" strategy="lazyOnload" />
        <Script src="/js/slider-radio.js" strategy="lazyOnload" />
        <Script src="/js/select2.min.js" strategy="lazyOnload" />
        <Script src="/js/smooth-scrollbar.js" strategy="lazyOnload" />
        <Script src="/js/jquery.magnific-popup.min.js" strategy="lazyOnload" />
        {/* <Script src="/js/plyr.min.js" strategy="lazyOnload" /> */}
        <Script src="/js/bootstrap.bundle.min.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}