import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './vendor.css';
import Script from 'next/script';
import { Header } from '../components/layout/Header';
import { Footer } from '../components/layout/Footer';
import NextAuthWrapper from '../services/nextauth.wrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {/* <Header /> */}
                <main>
                    <NextAuthWrapper>{children}</NextAuthWrapper>
                </main>
                {/* <Footer /> */}
                <Script
                    src="/js/jquery-3.5.1.min.js"
                    strategy="beforeInteractive"
                />
                <Script
                    src="/js/bootstrap.bundle.min.js"
                    strategy="afterInteractive"
                />
                <Script
                    src="/js/owl.carousel.min.js"
                    strategy="afterInteractive"
                />
                <Script src="/js/slider-radio.js" strategy="afterInteractive" />
                <Script src="/js/select2.min.js" strategy="afterInteractive" />
                <Script
                    src="/js/smooth-scrollbar.js"
                    strategy="afterInteractive"
                />
                <Script
                    src="/js/jquery.magnific-popup.min.js"
                    strategy="afterInteractive"
                />
                <Script src="/js/plyr.min.js" strategy="afterInteractive" />
                <Script src="/js/main.js" strategy="afterInteractive" />
            </body>
        </html>
    );
}
